### ISSUE TITLE
Translation bugs

### ISSUE THREAD

**Issue by Kav-K** [Kav-K/GPTDiscord#399]
![CleanShot 2023-11-11 at 21 03 18](https://github.com/Kav-K/GPTDiscord/assets/21161101/c4c80822-bd07-46c6-a06c-bec56f26cc40)

When launched from the context menu this vietnamese text wasn't translated (I'm thinking issue with auto detection?)

**Comment by cherryroots** [comment]
DeepL doesn't have Vietnamese as an option, it'd probably be preferable to just switch out the entire thing with google translate sometime because it just has support for more languages, and deepl api isn't available in every country.

![image](https://github.com/Kav-K/GPTDiscord/assets/15952522/3940ed55-6993-47e6-8daa-cc0616324094)

**Comment by Kav-K** [comment]
Facts
